config/routes.rb
Rails.application.routes.draw do
  shallow do
    resources :games do
      resources :frames
    end
  end

end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :game

  validates :first, presence: true
  validates :frame, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: 12 }

  validates_format_of :first, with: /\A((x|X)|(f|F)|(s|S)?[0-9]{1}|10)\z/
  validates_format_of :second, with: /\A((x|X)|(f|F)|[0-9]{1}|10||\/)\z/, allow_blank: true

  before_save :convert_first
  before_save :convert_second if self.second.present?

  def total
    total = second.presence ? convert_first + convert_second : convert_first unless twelfth?
    total = convert_first if twelfth?
    total
  end

  def strike?
    first.to_i == 10
  end

  def spare?
    return false unless second.presence
    first.to_i != 10 && first.to_i + second.to_i == 10
  end

  def open?
    !strike? && !spare?
  end

  def fill?
    !open?
  end

  def twelfth?
    frame == 12
  end

  def eleventh?
    frame == 11
  end

  def convert_first
    self.split = true if self.first.downcase.include? 's'
    self.first = Frame.convert_to_number(self.first)
  end

  def convert_second
    self.second = self.second == '/' ? 10 - self.first.to_i : Frame.convert_to_number(self.second)
  end

  private

  def self.convert_to_number(string)
    return 0 if string.downcase == 'f'
    return 10 if string.downcase == 'x'
    /(\d{1,2})/.match(string).to_a[0].to_i
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessor :score_map

  has_many :frames

  validates :score, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 300 }
  validates :handicap, numericality: { only_integer: true,
                                       allow_blank: true }

  def finalize_game
    score_game
    total_frames
  end

  private

  def score_game
    @score_map = []
    self.frames.each_with_index do |frame, index|
      running_total = @score_map[-1] ? @score_map[-1] : 0
      if index <= 8
        total_normal_frame(frame, running_total, index) if index
      elsif index == 9
        total_tenth_frame
      end
    end
    self.score = @score_map[-1]
  end

  def total_normal_frame(frame, running_total, index)
    if frame.strike?
      @score_map.push(running_total + score_strike(index))
    elsif frame.spare?
      @score_map.push(running_total + score_spare(index))
    else
      @score_map.push(running_total + score_open(index))
    end
  end

  def total_tenth_frame
    tenth_frame = self.frames[9]
    eleventh_frame = self.frames[10]
    twelfth_frame = self.frames[11]

    score = 0
    score += tenth_frame.first.to_i
    score += tenth_frame.second.to_i if tenth_frame.second.present?
    score += eleventh_frame.first.to_i if eleventh_frame && eleventh_frame.first.present?
    score += eleventh_frame.second.to_i if eleventh_frame && eleventh_frame.second.present?
    score += twelfth_frame.first.to_i if twelfth_frame && twelfth_frame.first.present?

    @score_map.push(@score_map[-1] + score)
  end

  def total_frames
    self.frames.each_with_index do |frame, index|
      frame.score = @score_map[index] if index <= 9
    end
  end

  def score_strike(index)
    frame = self.frames[index + 1]
    next_frame = self.frames[index + 2]
    10 + frame.first.to_i + (frame.second ? frame.second : next_frame.first).to_i
  end

  def score_spare(index)
    10 + self.frames[index + 1].first.to_i
  end

  def score_open(index)
    self.frames[index].first.to_i + self.frames[index].second.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
  before_action :set_frame, only: [:show, :edit, :update, :destroy]
  before_action :set_game, only: [:index, :new, :create]

  # GET /frames
  # GET /frames.json
  def index
    @frames = @game.frames
  end

  # GET /frames/1
  # GET /frames/1.json
  def show
  end

  # GET /frames/new
  def new
    @frame = Frame.new
  end

  # GET /frames/1/edit
  def edit
  end

  # POST /frames
  # POST /frames.json
  def create
    @frame = Frame.new(frame_params)

    respond_to do |format|
      if @frame.save
        format.html { redirect_to @frame, notice: 'Frame was successfully created.' }
        format.json { render :show, status: :created, location: @frame }
      else
        format.html { render :new }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frames/1
  # PATCH/PUT /frames/1.json
  def update
    respond_to do |format|
      if @frame.update(frame_params)
        format.html { redirect_to @frame, notice: 'Frame was successfully updated.' }
        format.json { render :show, status: :ok, location: @frame }
      else
        format.html { render :edit }
        format.json { render json: @frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frames/1
  # DELETE /frames/1.json
  def destroy
    @frame.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Frame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame
      @frame = Frame.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frame_params
      params.require(:frame).permit(:frame, :first, :second)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:score, :handicap)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/frames/_form.html.erb
<%= form_for(@frame) do |f| %>
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frame.errors.count, "error") %> prohibited this frame from being saved:</h2>

      <ul>
      <% @frame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :frame %><br>
    <%= f.number_field :frame %>
  </div>
  <div class="field">
    <%= f.label :first %><br>
    <%= f.number_field :first %>
  </div>
  <div class="field">
    <%= f.label :second %><br>
    <%= f.number_field :second %>
  </div>
  <div class="field">
    <%= f.label :third %><br>
    <%= f.number_field :third %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frames/edit.html.erb
<h1>Editing Frame</h1>

<%= render 'form' %>

<%= link_to 'Show', @frame %> |
<%= link_to 'Back', frames_path %>

app/views/frames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Frames</h1>

<table>
  <thead>
    <tr>
      <th>Frame</th>
      <th>First</th>
      <th>Second</th>
      <th>Third</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frames.each do |frame| %>
      <tr>
        <td><%= frame.frame %></td>
        <td><%= frame.first %></td>
        <td><%= frame.second %></td>
        <td><%= frame.third %></td>
        <td><%= frame.score %></td>
        <td><%= link_to 'Show', frame %></td>
        <td><%= link_to 'Edit', edit_frame_path(frame) %></td>
        <td><%= link_to 'Destroy', frame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frame', new_game_frame_path %>

app/views/frames/new.html.erb
<h1>New Frame</h1>

<%= render 'form' %>

<%= link_to 'Back', frames_path %>

app/views/frames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frame:</strong>
  <%= @frame.frame %>
</p>

<p>
  <strong>First:</strong>
  <%= @frame.first %>
</p>

<p>
  <strong>Second:</strong>
  <%= @frame.second %>
</p>

<p>
  <strong>Third:</strong>
  <%= @frame.third %>
</p>

<p>
  <strong>Score:</strong>
  <%= @frame.score %>
</p>

<%= link_to 'Edit', edit_frame_path(@frame) %> |
<%= link_to 'Back', frames_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.score %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @game.score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BowlingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>